version: 2.1
orbs:
  node: circleci/node@2.1.0
jobs:
  build-and-test:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - setup_remote_docker
      
  test-server:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ./server
      - run:
          command: npm install
          working_directory: ./server
      - run:
          command: npm test
          working_directory: ./server
          
  test-client:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          command: npm install
          working_directory: ./client
      - run:
          command: npm test
          working_directory: ./client
  
  docker:
    machine: true
    steps:
       - checkout
       - run:
           command: |
              echo "$DOCKERHUB_PASSWORD" | docker login -u "aleksos54" --password-stdin
              sudo docker build ./db -t aleksos54/node-react-db
              sudo docker push aleksos54/node-react-db:latest
              
       - run:
           command: |
              echo "$DOCKERHUB_PASSWORD" | docker login -u "aleksos54" --password-stdin
              sudo docker build ./server -t aleksos54/node-svr
              sudo docker push aleksos54/node-svr
              
       - run:
           command: |
              echo "$DOCKERHUB_PASSWORD" | docker login -u "aleksos54" --password-stdin
              sudo docker build ./client -t aleksos54/cra-client
              sudo docker push aleksos54/cra-client
          
            
      
            
workflows:
    build-and-test:
      jobs:
        - build
        - test-server:
           requires:
               - build
        - test-client:
           requires:
               - build
        - docker:
           requires:
           - test-server
           - test-client
